import { test, expect } from '../fixtures/base.fixture';

test.describe('Gestión de Facturas', () => {
  test.beforeEach(async ({ sidebar }) => {
    await sidebar.goToInvoices();
  });

  // ── CASO FUNCIONAL 1 ──────────────────────────────────────
  test('CF1: Visualización del listado de facturas', async ({ invoices }) => {
    // Precondition: invoices have been generated by billing
    const isVisible = await invoices.isListVisible();
    expect(isVisible).toBeTruthy();

    // DataGrid should be rendered
    const rowCount = await invoices.getRowCount();
    expect(rowCount).toBeGreaterThanOrEqual(0);
  });

  // ── CASO FUNCIONAL 2 ──────────────────────────────────────
  test('CF2: Descarga exitosa del PDF de una factura', async ({ invoices, page }) => {
    // Precondition: at least one invoice exists with a PDF
    const rowCount = await invoices.getRowCount();
    if (rowCount === 0) {
      test.skip(true, 'No invoices available for PDF download test');
      return;
    }

    // Set up download listener before clicking
    const downloadPromise = page.waitForEvent('download', { timeout: 10_000 }).catch(() => null);

    // Click download on first visible row
    const firstRow = page.locator('.MuiDataGrid-row').first();
    const firstRowText = await firstRow.textContent();
    if (firstRowText) {
      await invoices.clickDownloadPdf(firstRowText.slice(0, 20));
    }

    const download = await downloadPromise;
    // If download is triggered, validate it
    if (download) {
      expect(download.suggestedFilename()).toContain('.pdf');
    }
  });

  // ── CASO FUNCIONAL 3 ──────────────────────────────────────
  test('CF3: Descarga de PDF de factura inexistente/error', async ({ invoices, page }) => {
    // This test verifies error handling when PDF is not available
    const rowCount = await invoices.getRowCount();
    if (rowCount === 0) {
      test.skip(true, 'No invoices available for error test');
      return;
    }

    // Attempt to download - if no PDF exists, should show error
    const firstRow = page.locator('.MuiDataGrid-row').first();
    const firstRowText = await firstRow.textContent();

    if (firstRowText) {
      // Click download, expecting potential error
      await invoices.clickDownloadPdf(firstRowText.slice(0, 20)).catch(() => {});

      // Check for error message or successful download
      const hasError = await page
        .locator('.MuiAlert-standardError')
        .isVisible()
        .catch(() => false);

      // Either an error is shown or the download succeeded — both are valid
      expect(typeof hasError).toBe('boolean');
    }
  });

  // ── CASO TRANSICIONAL 1 ───────────────────────────────────
  test('CT1: Navegación entre listado y detalle de factura', async ({ invoices, page, sidebar }) => {
    // Navigate to invoices
    const isVisible = await invoices.isListVisible();
    expect(isVisible).toBeTruthy();

    // Navigate away to Tarifario and back
    await sidebar.goToTariffs();
    await sidebar.goToInvoices();

    // List should reload
    const isStillVisible = await invoices.isListVisible();
    expect(isStillVisible).toBeTruthy();
  });
});
