package com.naturgy.gas;

import com.naturgy.gas.repository.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Smoke test: verifies the application context loads, seed runs,
 * and all tables contain the expected number of rows from the sample CSVs.
 */
@SpringBootTest
class SmokeTest {

    @Autowired
    private SupplyPointRepository supplyPointRepository;

    @Autowired
    private GasTariffRepository gasTariffRepository;

    @Autowired
    private GasConversionFactorRepository gasConversionFactorRepository;

    @Autowired
    private TaxConfigRepository taxConfigRepository;

    @Autowired
    private GasReadingRepository gasReadingRepository;

    @Autowired
    private InvoiceRepository invoiceRepository;

    @Test
    void contextLoads() {
        // just verifying the context starts up correctly
    }

    @Test
    void supplyPointsSeedLoaded() {
        long count = supplyPointRepository.count();
        assertThat(count).as("supply_points should have 3 rows from sample CSV").isEqualTo(3);
    }

    @Test
    void gasTariffsSeedLoaded() {
        long count = gasTariffRepository.count();
        assertThat(count).as("gas_tariffs should have 3 rows from sample CSV").isEqualTo(3);
    }

    @Test
    void gasConversionFactorsSeedLoaded() {
        long count = gasConversionFactorRepository.count();
        assertThat(count).as("gas_conversion_factors should have 4 rows from sample CSV").isEqualTo(4);
    }

    @Test
    void taxesSeedLoaded() {
        long count = taxConfigRepository.count();
        assertThat(count).as("tax_configs should have 1 row from sample CSV").isEqualTo(1);
    }

    @Test
    void gasReadingsSeedLoaded() {
        long count = gasReadingRepository.count();
        // Sample CSV has 11 rows (including ES0021000000003CD which has no matching supply point but is still stored)
        assertThat(count).as("gas_readings should have 11 rows from sample CSV").isEqualTo(11);
    }

    @Test
    void invoiceTableStartsEmpty() {
        long count = invoiceRepository.count();
        assertThat(count).as("invoices table should start empty (generated by billing logic)").isEqualTo(0);
    }

    @Test
    void seedIsIdempotent() {
        // Running seed a second time should not duplicate any data
        long supplyBefore = supplyPointRepository.count();
        long tariffBefore = gasTariffRepository.count();
        long convBefore = gasConversionFactorRepository.count();
        long taxBefore = taxConfigRepository.count();
        long readingsBefore = gasReadingRepository.count();

        // Re-trigger seed via a new seeder instance
        com.naturgy.gas.seed.DataSeeder seeder = new com.naturgy.gas.seed.DataSeeder(
                supplyPointRepository, gasTariffRepository,
                gasConversionFactorRepository, taxConfigRepository, gasReadingRepository);
        seeder.run(null);

        assertThat(supplyPointRepository.count()).isEqualTo(supplyBefore);
        assertThat(gasTariffRepository.count()).isEqualTo(tariffBefore);
        assertThat(gasConversionFactorRepository.count()).isEqualTo(convBefore);
        assertThat(taxConfigRepository.count()).isEqualTo(taxBefore);
        assertThat(gasReadingRepository.count()).isEqualTo(readingsBefore);
    }
}
